{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dce-template-engine.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.svc }}@{{ .Values.job.project }}.iam.gserviceaccount.com
  labels:
  {{- include "dce-template-engine.labels" . | nindent 4 }}
{{- end }}
