# Default values for dce-template-rules
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxUnavailable: 0

image:
  repository: eu.gcr.io/sbs-ctl-bld-01-54a6/dmg/dce-template-views
  tag: latest
  pullPolicy: Always

container:
  name: sbs-dmg-dce-template-views

config:
  projectId: sbs-dmg-bld-01-c332
  dataset: sbs_dmg_bld_bqd_euwe2_data_control_engine


imagePullSecrets: []
nameOverride: dce-template-views
fullnameOverride: dce-template-views

pod:
  annotations: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000

serviceAccount:
  name: sa-kcl-dmn01-rskcda-dce
  svc: svc-dmn01-rskcda-dce
  automountServiceAccountToken: true

viewLables:
  # The following values define the lables which are set on newley created views
  # They should be a colon seperated list (i.e. "key:value")
  - cmdb_appid:al15407
  - component:data-control-engine
  - owner:sbs-dmg
  - troux_id:sbs-dmg
  - cost_centre:c-pr0101-s1-91
  - dataclassification:confidential

roleBinding:
  name: rb-kcl-sbs-dmg-views

resources:
  limits:
    cpu: "4"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
