# Default values for dce-template-rules
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxUnavailable: 0

image:
  repository: eu.gcr.io/sbs-ctl-bld-01-54a6/dmg/dce-template-data
  tag: latest
  pullPolicy: Always

container:
  name: sbs-dmg-dce-template-data

config:
  projectId: sbs-dmg-bld-01-c332
  bucket: sbs-dmg-bld-01-stb-euwe2-dmg-data-control-engine
  dataset: sbs_dmg_bld_bqd_euwe2_data_control_engine

imagePullSecrets: []
nameOverride: dce-template-data
fullnameOverride: dce-template-data

pod:
  annotations: {}
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000

serviceAccount:
  name: sa-kcl-dmn01-rskcda-dce
  svc: svc-dmn01-rskcda-dce

roleBinding:
  name: rb-kcl-sbs-dmg-data

resources:
  limits:
    cpu: "4"
    memory: 4Gi
  requests:
    cpu: "1"
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
