# -------------- Final image --------------
FROM harbor.mgmt-bld.oncp.dev/sbs_dmg_rtl/sbs-dmg-data-control-engine:release_v0.41.0 as final
LABEL workstream="dmn01-rskcda" \
    maintainer="dmn01-rskcda" \
    email="jacob.harden@e.lloydsbanking.com"
