# Default values for dce-template-views.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
maxUnavailable: 0

image:
  repository: eu.gcr.io/dmn01-rskctl-bld-01-2fd1/rsk/dce-template-views
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion. Jenkins replaces this tag value.
  tag: latest

config:
  projectId: dmn01-rsksoi-bld-01-2017
  dataset: dmn01_rsk_data_control

viewLables:
  # The following values define the lables which are set on newley created views
  # They should be a colon seperated list (i.e. "key:value")
  - cmdb_appid:al15407
  - component:data-control-engine
  - owner:sbs-dmg
  - troux_id:sbs-dmg
  - cost_centre:c-pr0101-s1-91
  - dataclassification:confidential

serviceAccount:
  name: sa-kcl-dmn01-rskcda-dce
  svc: svc-dmn01-rskcda-dce
  automountServiceAccountToken: true

resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: "1"
    memory: 2Gi

