SELECT
    IFNULL(ACBS_GCP.CLMS_LOAN_CCY, ACBS_FILE.CLMS_LOAN_CCY) as CLMS_LOAN_CCY,
    CASE
      WHEN ACBS_FILE.DATE IS NULL THEN ACBS_GCP.CLMS_CMR_PRINCIPAL
      WHEN ACBS_GCP.DATE >= ACBS_FILE.DATE THEN ACBS_GCP.CLMS_CMR_PRINCIPAL
      WHEN ACBS_GCP.DATE IS NULL THEN 0
      WHEN ACBS_GCP.DATE < ACBS_FILE.DATE THEN 0
    END as ACBS_GCP_TOTALS,
    CASE
      WHEN ACBS_GCP.DATE IS NULL THEN ACBS_FILE.CLMS_CMR_PRINCIPAL
      WHEN ACBS_GCP.DATE <= ACBS_FILE.DATE THEN ACBS_FILE.CLMS_CMR_PRINCIPAL
      WHEN ACBS_FILE.DATE IS NULL THEN 0
      WHEN ACBS_GCP.DATE > ACBS_FILE.DATE THEN 0
	  END as ACBS_FILE_TOTALS,
	  CASE
	    WHEN ACBS_GCP.DATE IS NULL THEN ACBS_FILE.DATE
      WHEN ACBS_FILE.DATE IS NULL THEN ACBS_GCP.DATE
	    WHEN ACBS_GCP.DATE > ACBS_FILE.DATE THEN ACBS_GCP.DATE
	    WHEN ACBS_GCP.DATE <= ACBS_FILE.DATE THEN ACBS_FILE.DATE
	  END DATE,
	  CASE
      WHEN ACBS_GCP.UPDATED_AT IS NULL THEN ACBS_FILE.UPDATED_AT
    	WHEN ACBS_FILE.UPDATED_AT IS NULL THEN ACBS_GCP.UPDATED_AT
    	WHEN ACBS_GCP.UPDATED_AT >= ACBS_FILE.UPDATED_AT THEN ACBS_GCP.UPDATED_AT
    	WHEN ACBS_GCP.UPDATED_AT < ACBS_FILE.UPDATED_AT THEN ACBS_FILE.UPDATED_AT
    END as UPDATED_AT,
    CASE
      WHEN ACBS_GCP.DATE IS NULL THEN ABS(ACBS_FILE.CLMS_CMR_PRINCIPAL)
      WHEN ACBS_FILE.DATE IS NULL THEN ABS(ACBS_GCP.CLMS_CMR_PRINCIPAL)
      WHEN ACBS_GCP.DATE = ACBS_FILE.DATE THEN ABS(ACBS_GCP.CLMS_CMR_PRINCIPAL - ACBS_FILE.CLMS_CMR_PRINCIPAL)
      WHEN ACBS_GCP.DATE < ACBS_FILE.DATE THEN ABS(ACBS_FILE.CLMS_CMR_PRINCIPAL)
      WHEN ACBS_GCP.DATE > ACBS_FILE.DATE THEN ABS(ACBS_GCP.CLMS_CMR_PRINCIPAL)
    END as DIFF
FROM ${DATASET}.test_eod_001_acbs ACBS_GCP
FULL OUTER JOIN ${DATASET}.test_eod_001_brownfield ACBS_FILE
  ON ACBS_GCP.CLMS_LOAN_CCY = ACBS_FILE.CLMS_LOAN_CCY
  AND ACBS_GCP.DATE = ACBS_FILE.DATE
ORDER BY CLMS_LOAN_CCY