SELECT
    IFNULL(GL.FILE_NAME, ACBS.FILE_NAME) as FILE_NAME,
	  IFNULL(GL.CO, CASE
      WHEN ACBS.CLMS_PORT_ID = 'I*+Z*+C*' THEN 4655
  	  WHEN ACBS.CLMS_PORT_ID = 'L*' THEN 433
  	  WHEN ACBS.CLMS_PORT_ID = 'B*' THEN 4439
    END) as PORT_ID,
    IFNULL(GL.BU, ACBS.CLMS_PROF_CENTRE) as PROF_CENTRE,
    IFNULL(GL.CCY, ACBS.CLMS_LOAN_CCY) as CCY,
    CASE
      WHEN GL.DATE IS NULL THEN 0
      WHEN GL.DATE >= ACBS.DATE THEN GL.BALANCE
      WHEN ACBS.DATE IS NULL THEN GL.BALANCE
      WHEN GL.DATE < ACBS.DATE THEN 0
    END as GL_BALANCE,
    CASE
      WHEN ACBS.DATE IS NULL THEN 0
      WHEN ACBS.DATE >= GL.DATE THEN ACBS.SUMIFS
      WHEN GL.DATE IS NULL THEN ACBS.SUMIFS
      WHEN ACBS.DATE < GL.DATE THEN 0
    END as ACBS_BALANCE,
	  CASE
      WHEN GL.DATE IS NULL THEN ACBS.DATE
      WHEN ACBS.DATE IS NULL THEN GL.DATE
      WHEN GL.DATE > ACBS.DATE THEN GL.DATE
      WHEN GL.DATE <= ACBS.DATE THEN ACBS.DATE
    END DATE,
    CASE
      WHEN GL.UPDATED_AT IS NULL THEN ACBS.UPDATED_AT
      WHEN ACBS.UPDATED_AT IS NULL THEN GL.UPDATED_AT
      WHEN GL.UPDATED_AT >= ACBS.UPDATED_AT THEN GL.UPDATED_AT
      WHEN GL.UPDATED_AT < ACBS.UPDATED_AT THEN ACBS.UPDATED_AT
    END as UPDATED_AT,
	  CASE
      WHEN GL.DATE IS NULL THEN ABS(ACBS.SUMIFS)
      WHEN ACBS.DATE IS NULL THEN ABS(GL.BALANCE)
      WHEN GL.DATE = ACBS.DATE THEN ABS(GL.BALANCE - ACBS.SUMIFS)
      WHEN GL.DATE < ACBS.DATE THEN ABS(ACBS.SUMIFS)
      WHEN GL.DATE > ACBS.DATE THEN ABS(GL.BALANCE)
    END as DIFF
FROM ${DATASET}.test_glo_001_gl GL
FULL OUTER JOIN ${DATASET}.test_glo_001_acbs ACBS
	ON GL.BU = ACBS.CLMS_PROF_CENTRE AND GL.CCY = ACBS.CLMS_LOAN_CCY
    AND GL.DATE = ACBS.DATE
	AND GL.FILE_NAME = ACBS.FILE_NAME AND GL.CO = CASE
	       WHEN ACBS.CLMS_PORT_ID = 'I*+Z*+C*' THEN 4655
	       WHEN ACBS.CLMS_PORT_ID = 'L*' THEN 433
	       WHEN ACBS.CLMS_PORT_ID = 'B*' THEN 4439
       END
ORDER BY CCY