apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name}}
  namespace: {{ .Release.Namespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.svc }}@{{ .Values.config.projectId }}.iam.gserviceaccount.com
