#Gross Value Variance Check

#rule_bindings:
#  COLLATERAL_T&L_CNTRLS_006:
#    table_name: nested_collateral
#    field_name: CollateralProductGrossValue
#    timestamp_field: val_load_datetime
#    rule_id: FRT_COLLATERAL_D_NUMBER_OF_DAYS
#    summary_message:
#      schema_sql_mapping:
#        collateral_charges.coll_charge_value: dimension1
#        collateral_facilities.cfl_allocation_value: dimension2
#    fail_message:
#      schema_sql_mapping:
#        collateral_charges.coll_charge_value: dimension1
#        collateral_facilities.cfl_allocation_value: dimension2
#      schema_values:
#        entity_id: ${dimension1}_>=_${dimension2}
